name: CI/CD pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install test dependencies
        run: pip3 install -r requirements-dev.txt

      - name: Run tests
        run: |
          pytest --cov=app --cov-report=html
          pytest -v --cov=app --cov-report=term

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
